import { SettlementRecord } from "./settlement-parser.js";

function stripCheckboxAndBackticks(text: string): string {
  // Strip checkbox markers (defensive — parser already strips them)
  let cleaned = text
    .replace(/^-\s+\[[ xX]\]\s+/, "")
    .replace(/^\*\s+\[[ xX]\]\s+/, "");
  // Strip backtick pairs around text segments
  cleaned = cleaned.replace(/`([^`]+)`/g, "$1");
  return cleaned.trim();
}

export function buildPrDraft(settlement: SettlementRecord): string {
  const date = new Date().toISOString().slice(0, 10);

  const cleanedCriteria = settlement.doneCriteria.map(stripCheckboxAndBackticks);

  const summaryItems =
    cleanedCriteria.length > 0
      ? cleanedCriteria.map((c) => `- ${c}`).join("\n")
      : "- (none)";

  const territoryItems =
    settlement.territoryIds.length > 0
      ? settlement.territoryIds.map((t) => `- \`${t}\``).join("\n")
      : "- (none)";

  const settlerItems =
    settlement.settlerIds.length > 0
      ? settlement.settlerIds.map((s) => `- \`${s}\``).join("\n")
      : "- (none)";

  const invariantItems =
    settlement.invariants.length > 0
      ? settlement.invariants.map((inv) => `- ${inv}`).join("\n")
      : "- (none)";

  const validationChecklist = [
    ...settlement.validationCommands.map((c) => `- [ ] ${c}`),
    ...cleanedCriteria.map((c) => `- [ ] ${c}`),
  ].join("\n") || "- [ ] (none)";

  const residualGapItems =
    settlement.residualGaps.length > 0
      ? settlement.residualGaps.map((g) => `- ${g}`).join("\n")
      : "- (none)";

  return `<!-- Generated by healthos-steward pr-draft -->
<!-- Settlement: ${settlement.id} -->
<!-- Generated: ${date} -->
<!-- Non-canonical: derived artifact, not an official doc -->

## Summary
${summaryItems}

## Territories involved
${territoryItems}

## Settler profiles assigned
${settlerItems}

## Invariants involved
${invariantItems}

## Validation checklist
${validationChecklist}

## Residual gaps
${residualGapItems}

## Non-claims
This PR review draft is a derived artifact generated by healthos-steward
from Settlement record fields. It does not authorize merge decisions,
clinical activity, runtime execution, or production-readiness claims.
All validation commands must pass before merging.

🤖 Generated by [healthos-steward pr-draft](https://github.com/myselfgus/HealthOScaffold)`;
}
