import type { TerritoryRecord } from "./territory-reader.js";
import type { SettlerRecord } from "./settler-reader.js";
import type { TrackerTask } from "./tracker-reader.js";

function nonCanonicalHeader(date: string): string {
  return `<!-- Derived memory — generated by healthos-steward build-memory -->
<!-- Generated: ${date} -->
<!-- NON-CANONICAL: official docs remain authoritative. This file is a
     derived snapshot for agent navigation only. Do not cite as evidence. -->
`;
}

export function buildIndex(files: string[], date: string): string {
  const rows = [
    ["construction-status.md", "ST task sequence with current status", "docs/execution/19-settler-model-task-tracker.md"],
    ["territory-index.md", "Territory registry snapshot", ".healthos-settler/territories/*.json"],
    ["settler-index.md", "Settler profile registry snapshot", ".healthos-settler/settlers/README.md"],
    ["settlement-index.md", "Active and completed Settlement listing", ".healthos-steward/settlements/"],
    ["handoff-snapshot.md", "Current handoff state", "docs/execution/12-next-agent-handoff.md"],
  ];

  const writtenSet = new Set(files);
  let table = "| File | Purpose | Primary source |\n";
  table += "|------|---------|----------------|\n";
  for (const [file, purpose, source] of rows) {
    const mark = writtenSet.has(file) ? "" : " (not written)";
    table += `| ${file}${mark} | ${purpose} | ${source} |\n`;
  }

  return `${nonCanonicalHeader(date)}
# Derived Memory Index

Generated: ${date}

This directory contains derived memory snapshots produced by \`healthos-steward build-memory\`.
Files are overwritten on each run. They are advisory summaries only — never cite them as evidence.

## Files

${table}
## Non-claims

These files do not replace official docs. Official docs under \`docs/\` remain authoritative.
Derived memory is for agent navigation and handoff acceleration only.
`;
}

export function buildConstructionStatus(tasks: TrackerTask[], date: string): string {
  let table = "| ID | Title | Status |\n";
  table += "|----|-------|--------|\n";
  for (const t of tasks) {
    table += `| ${t.id} | ${t.title} | ${t.status} |\n`;
  }

  const doneCount = tasks.filter((t) => t.status === "DONE").length;
  const total = tasks.length;
  const nextTodo = tasks.find((t) => t.status === "TODO");
  const nextLine = nextTodo
    ? `Next TODO: ${nextTodo.id} — ${nextTodo.title}.`
    : "No TODO tasks found.";

  return `${nonCanonicalHeader(date)}
# Construction Status

Generated: ${date}
Source: docs/execution/19-settler-model-task-tracker.md

## ST Task Sequence

${table}
## Summary

${doneCount} of ${total} tasks DONE. ${nextLine}
`;
}

export function buildTerritoryIndex(territories: TerritoryRecord[], date: string): string {
  let table = "| ID | Name | Maturity | Canonical docs (count) |\n";
  table += "|----|------|----------|------------------------|\n";
  for (const t of territories) {
    table += `| ${t.id} | ${t.name} | ${t.maturity} | ${t.canonicalDocs.length} |\n`;
  }

  return `${nonCanonicalHeader(date)}
# Territory Index

Generated: ${date}
Source: .healthos-settler/territories/*.json

## Territories

${table}
## Non-claims

Territory records are construction metadata only. Official docs remain canonical.
`;
}

export function buildSettlerIndex(settlers: SettlerRecord[], date: string): string {
  let table = "| Profile ID | Territory ID | Maturity |\n";
  table += "|------------|-------------|----------|\n";
  for (const s of settlers) {
    table += `| ${s.id} | ${s.territoryId} | ${s.maturity} |\n`;
  }

  return `${nonCanonicalHeader(date)}
# Settler Profile Index

Generated: ${date}
Source: .healthos-settler/settlers/README.md

## Settler Profiles

${table}
## Non-claims

Settler profiles are engineering instruction documents only.
They do not implement executable agents, runtime actors, or authority surfaces.
`;
}

export function buildSettlementIndex(
  active: Array<{ id: string; title: string; status: string }>,
  completed: Array<{ id: string; title: string; status: string }>,
  date: string
): string {
  function table(rows: Array<{ id: string; title: string; status: string }>): string {
    if (rows.length === 0) return "(none)\n";
    let t = "| ID | Title | Status |\n";
    t += "|----|-------|--------|\n";
    for (const r of rows) {
      t += `| ${r.id} | ${r.title} | ${r.status} |\n`;
    }
    return t;
  }

  return `${nonCanonicalHeader(date)}
# Settlement Index

Generated: ${date}
Source: .healthos-steward/settlements/

## Active Settlements

${table(active)}
## Completed Settlements

${table(completed)}
## Non-claims

Settlement records document engineering work units. They do not authorize clinical activity,
runtime execution, merge decisions, or production-readiness claims.
`;
}

export function buildHandoffSnapshot(
  handoffRaw: string,
  tasks: TrackerTask[],
  date: string
): string {
  const doneCount = tasks.filter((t) => t.status === "DONE").length;
  const todoCount = tasks.filter((t) => t.status === "TODO").length;
  const nextTodo = tasks.find((t) => t.status === "TODO");
  const nextLine = nextTodo
    ? `Next: ${nextTodo.id} — ${nextTodo.title}.`
    : "No TODO tasks found.";

  const first30 = handoffRaw.split("\n").slice(0, 30).join("\n");

  return `${nonCanonicalHeader(date)}
# Handoff Snapshot

Generated: ${date}

## Source

Generated from docs/execution/12-next-agent-handoff.md and
docs/execution/19-settler-model-task-tracker.md

## Construction phase summary

DONE: ${doneCount} tasks. TODO: ${todoCount} tasks. ${nextLine}

## Handoff note (first 30 lines)

${first30}

## Non-claims

This snapshot does not replace docs/execution/12-next-agent-handoff.md.
Official docs remain authoritative. This file is a derived snapshot for agent navigation only.
`;
}
