import type { SettlementRecord } from "./settlement-parser.js";
import type { TerritoryRecord } from "./territory-reader.js";
import type { SettlerRecord } from "./settler-reader.js";

export interface AssemblyInput {
  settlement: SettlementRecord;
  territories: TerritoryRecord[];
  settlers: SettlerRecord[];
}

// Hard-coded constant — never varies per Settlement.
// Copied verbatim from .healthos-steward/prompts/prompt-architecture-template.md
const CANONICAL_NOMENCLATURE = `Use current canonical HealthOS nomenclature.
System/product side:
- HealthOS = the sovereign operational environment for health systems.
- HealthOScaffold = historical construction repository name.
- Core = sovereign law-bearing layer.
- GOS = Governed Operational Spec.
- Session Runtime = Swift SessionRunner layer.
- \`HealthOSSessionRuntime\` = Swift module name.
- AACI = Swift runtime peer to MSR under SessionRunner.
- MSR = Mental Space Runtime, ASL → VDLP → GEM.
- Providers = infrastructure layer, not authority.
- Async Runtime = TypeScript async substrate.
- User-Agent Runtime = TypeScript user-agent runtime.
- Service Runtime = TypeScript service/operations workflow runtime.
- Scribe = documentation/capture interface.
- Sortio = patient sovereignty interface.
- CloudClinic = professional/service operations interface.
Construction side:
- Steward = construction coordinator.
- Settler = specialized engineering profile.
- Territory = repository domain.
- Settlement = bounded construction work unit.
- HealthOS Forge MCP = repository-maintenance MCP/tool surface.
- \`healthos-forge-mcp\` = package/server name for Forge MCP.
Do not use deprecated names as canonical.
Do not use:
- \`HealthOSFirstSliceSupport\`
- \`healthos-mcp\` as canonical construction MCP name
- scaffold as separate product identity
- Forge MCP as clinical/runtime MCP`;

const STANDARD_CONSTRUCTION_BOUNDARY = `The assembling agent and the implementing agent are both construction-system actors.
Neither has clinical authority, Core law authority, merge authority, or runtime behavior scope.
- No prompt generated by this system authorizes clinical activity, runtime execution, or production deployment.
- Construction tooling (Steward, Settlers, Settlements, Territories, HealthOS Forge MCP) is outside the HealthOS clinical/runtime hierarchy.
- Official docs (\`docs/architecture/\`, \`docs/execution/\`) remain canonical. Generated PromptSpecs are derived artifacts.
- Generated PromptSpecs inherit all HealthOS invariants; they do not grant authority beyond the referenced Settlement.`;

const STANDARD_TRACKING_DOCS = [
  "docs/execution/02-status-and-tracking.md",
  "docs/execution/19-settler-model-task-tracker.md",
  "docs/execution/22-steward-construction-operating-model.md",
];

function deduplicateOrdered(items: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const item of items) {
    if (!seen.has(item)) {
      seen.add(item);
      result.push(item);
    }
  }
  return result;
}

function slugFromId(settlementId: string): string {
  return settlementId.replace(/^SETTLEMENT-\d{8}-/i, "").toLowerCase();
}

function section(tag: string, content: string): string {
  const body = content.trim() || "<!-- no data from Settlement -->";
  return `<${tag}>\n${body}\n</${tag}>`;
}

function bulletList(items: string[]): string {
  if (items.length === 0) return "<!-- no data from Settlement -->";
  return items.map((i) => `- ${i}`).join("\n");
}

function numberedList(items: string[]): string {
  if (items.length === 0) return "<!-- no data from Settlement -->";
  return items.map((i, n) => `${n + 1}. ${i}`).join("\n");
}

function buildSystemRole(s: SettlementRecord): string {
  return [
    `You are an engineering agent working inside the \`myselfgus/HealthOScaffold\``,
    `repository — the historical construction repository for HealthOS.`,
    `You are executing task: ${s.title} (Settlement ID: ${s.id}).`,
    ``,
    `This is a construction-system work unit. You are non-clinical, non-constitutional,`,
    `non-authorizing, and have no merge authority.`,
    ``,
    `Territories: ${s.territoryIds.join(", ") || "(none)"}`,
    `Settler profiles: ${s.settlerIds.join(", ") || "(none)"}`,
  ].join("\n");
}

function buildMission(s: SettlementRecord): string {
  return s.objective || "<!-- no objective found in Settlement -->";
}

function buildContext(s: SettlementRecord, territories: TerritoryRecord[]): string {
  const lines: string[] = [
    "ST-010 through ST-014: DONE.",
    "",
    `Current Settlement: ${s.id}`,
    `Title: ${s.title}`,
    `Status: ${s.status || "UNKNOWN"}`,
    "",
    "Territory maturity:",
  ];
  if (territories.length === 0) {
    lines.push("  <!-- no territories loaded -->");
  } else {
    for (const t of territories) {
      lines.push(`  ${t.id}: ${t.maturity || "(unknown)"}`);
    }
  }
  if (s.settlerIds.length > 0) {
    lines.push("");
    lines.push(`Settler profiles assigned: ${s.settlerIds.join(", ")}`);
  }
  return lines.join("\n");
}

function buildCriticalPrecondition(s: SettlementRecord): string {
  const lines: string[] = [];
  if (s.filesInScope.length > 0) {
    lines.push("Confirm the following files exist before writing. If any are missing, stop and report:");
    for (const f of s.filesInScope) {
      lines.push(`  - Confirm \`${f}\` exists or is to be created.`);
    }
  } else {
    lines.push("<!-- no files-in-scope listed in Settlement -->");
  }
  if (s.invariants.length > 0) {
    lines.push("");
    lines.push("Precondition invariants (must not be violated):");
    for (const inv of s.invariants) {
      lines.push(`  - ${inv}`);
    }
  }
  return lines.join("\n");
}

function buildRequiredReading(s: SettlementRecord, territories: TerritoryRecord[]): string {
  const allDocs: string[] = ["docs/execution/22-steward-construction-operating-model.md"];
  for (const t of territories) {
    allDocs.push(...t.canonicalDocs);
  }
  allDocs.push(...s.sourceDocs);
  const deduped = deduplicateOrdered(allDocs);
  return numberedList(deduped.map((d) => `\`${d}\``));
}

function buildBoundaries(s: SettlementRecord, territories: TerritoryRecord[]): string {
  const lines: string[] = [STANDARD_CONSTRUCTION_BOUNDARY];
  if (s.invariants.length > 0) {
    lines.push("");
    lines.push("Settlement invariants:");
    s.invariants.forEach((inv, i) => lines.push(`${i + 1}. ${inv}`));
  }
  for (const t of territories) {
    if (t.invariants.length > 0) {
      lines.push("");
      lines.push(`Territory '${t.id}' invariants:`);
      t.invariants.forEach((inv, i) => lines.push(`${i + 1}. ${inv}`));
    }
  }
  return lines.join("\n");
}

function buildTaskGoals(s: SettlementRecord): string {
  if (s.doneCriteria.length === 0) return "<!-- no done-criteria found in Settlement -->";
  return s.doneCriteria
    .map((c, i) => `GOAL ${i + 1}: ${c}`)
    .join("\n");
}

function buildAllowedFiles(s: SettlementRecord): string {
  const lines: string[] = [];
  if (s.filesInScope.length > 0) {
    lines.push("Files in scope (CREATE or UPDATE as needed):");
    for (const f of s.filesInScope) {
      lines.push(`  ${f}`);
    }
  } else {
    lines.push("<!-- no files-in-scope listed in Settlement -->");
  }
  lines.push("");
  lines.push("Always update tracking docs:");
  for (const d of STANDARD_TRACKING_DOCS) {
    lines.push(`  ${d}`);
  }
  if (s.restrictions.length > 0) {
    lines.push("");
    lines.push("DO NOT TOUCH (per Settlement restrictions):");
    for (const r of s.restrictions) {
      lines.push(`  - ${r}`);
    }
  }
  return lines.join("\n");
}

function buildForbiddenScope(s: SettlementRecord): string {
  const items: string[] = [...s.restrictions];
  items.push("Do not push directly to main.");
  items.push("Do not implement healthos-forge-mcp unless this Settlement explicitly targets it.");
  return bulletList(items);
}

function buildImplRequirements(s: SettlementRecord, territories: TerritoryRecord[]): string {
  const lines: string[] = [];
  if (s.doneCriteria.length > 0) {
    lines.push("Explicit requirements derived from done-criteria:");
    s.doneCriteria.forEach((c, i) => lines.push(`${i + 1}. ${c}`));
  }
  const gapTerritories = territories.filter((t) => t.knownGaps.length > 0);
  if (gapTerritories.length > 0) {
    lines.push("");
    lines.push("Known gaps in referenced territories (context only — do not close gaps not assigned to this Settlement):");
    for (const t of gapTerritories) {
      lines.push(`Territory '${t.id}':`);
      for (const g of t.knownGaps) {
        lines.push(`  - ${g}`);
      }
    }
  }
  return lines.join("\n") || "<!-- no requirements data from Settlement -->";
}

function buildTrackingUpdates(s: SettlementRecord): string {
  const residualList =
    s.residualGaps.length > 0
      ? s.residualGaps.map((g) => `  - ${g}`).join("\n")
      : "  (none identified)";
  return [
    `After all validation passes, update the following tracking docs:`,
    ``,
    `1. \`docs/execution/02-status-and-tracking.md\``,
    `   Add entry: ${s.id} — ${s.title} — Status: DONE`,
    `   Include: files created/updated, validation commands run and results,`,
    `   invariants preserved, maturity level, residual gaps.`,
    ``,
    `2. \`docs/execution/19-settler-model-task-tracker.md\``,
    `   Find the entry for this Settlement and mark Status: DONE.`,
    `   Add Outcome block describing what was created/updated.`,
    ``,
    `3. \`docs/execution/22-steward-construction-operating-model.md\``,
    `   Update the planned task sequence to mark ${s.id} as DONE.`,
    `   Add a note describing what was delivered and what the next task is.`,
    ``,
    `Residual gaps to record:`,
    residualList,
    ``,
    `Mark this Settlement DONE only after all validation passes or all`,
    `pre-existing failures are explicitly recorded with exact command output.`,
  ].join("\n");
}

function buildValidationRequired(s: SettlementRecord): string {
  const cmds = [...s.validationCommands];
  if (!cmds.includes("make validate-docs")) cmds.push("make validate-docs");
  if (!cmds.includes("make validate-all")) cmds.push("make validate-all");
  return numberedList(cmds.map((c) => `\`${c}\``));
}

function buildGitWorkflow(s: SettlementRecord): string {
  const slug = slugFromId(s.id);
  const branch = `feat/${slug}`;
  const prTitle = `feat(construction): ${s.title}`;
  const summaryLine = s.objective.split(/[.\n]/)[0]?.trim() ?? s.title;
  const residualStr =
    s.residualGaps.length > 0
      ? s.residualGaps.map((g) => `  - ${g}`).join("\n")
      : "  (none identified)";
  return [
    `# 1. Start clean`,
    `git checkout main && git pull origin main`,
    ``,
    `# 2. Create branch`,
    `git checkout -b ${branch}`,
    ``,
    `# 3. Implement the task goals`,
    ``,
    `# 4. Stage files in scope`,
    s.filesInScope.map((f) => `git add ${f}`).join("\n") ||
      "# (stage relevant created/updated files)",
    ``,
    `# 5. Commit`,
    `git commit -m "$(cat <<'EOF'`,
    `feat(construction): ${s.title}`,
    ``,
    `${summaryLine}.`,
    ``,
    `Invariants: construction-system boundary preserved; no clinical authority;`,
    `  no merge authority; no runtime behavior changed.`,
    `Residual gaps:`,
    residualStr,
    ``,
    `Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>`,
    `EOF`,
    `)"`,
    ``,
    `# 6. Push and open PR`,
    `git push -u origin ${branch}`,
    ``,
    `gh pr create \\`,
    `  --title "${prTitle}" \\`,
    `  --body "$(cat <<'EOF'`,
    `## Summary`,
    `- ${summaryLine}`,
    ``,
    `## Invariants`,
    `- Construction-system boundary preserved`,
    `- No clinical authority, no merge authority, no runtime scope`,
    `- Official docs remain canonical`,
    ``,
    `## Validation`,
    s.validationCommands.map((c) => `- [ ] \`${c}\` PASS`).join("\n") ||
      "- [ ] make validate-docs PASS\n- [ ] make validate-all PASS",
    ``,
    `## Residual gaps`,
    residualStr,
    ``,
    `🤖 Generated with [Claude Code](https://claude.com/claude-code)`,
    `EOF`,
    `)"`,
  ].join("\n");
}

function buildSelfValidationChecklist(s: SettlementRecord): string {
  const standard = [
    "[ ] Only the intended Settlement task was executed — no scope drift",
    "[ ] Canonical nomenclature used throughout (HealthOS Forge MCP, healthos-forge-mcp, HealthOSSessionRuntime)",
    "[ ] No deprecated names reintroduced (no healthos-mcp, no HealthOSFirstSliceSupport)",
    "[ ] No runtime behavior changed unless this Settlement explicitly targets it",
    "[ ] No clinical authority introduced",
    "[ ] No production-readiness or regulatory claim added",
    "[ ] Official docs remain canonical; generated PromptSpec is a derived artifact",
    "[ ] Tracking docs updated (02-status-and-tracking.md, 19-settler-model-task-tracker.md, 22-steward-construction-operating-model.md)",
    "[ ] Validation results recorded honestly — no masking of failures",
    "[ ] Work happened on branch + PR; no direct push to main",
  ];
  const criteriaItems = s.doneCriteria.map((c) => `[ ] ${c}`);
  return [...standard, ...criteriaItems].join("\n");
}

function buildFinalResponse(s: SettlementRecord): string {
  return [
    `Report the following after completing the task:`,
    ``,
    `1. Branch name`,
    `2. PR URL`,
    `3. Files created (list all new files)`,
    `4. Files updated (list all modified files)`,
    `5. Summary of work completed`,
    `6. Validation commands run and their exact results`,
    `7. Task status: DONE / BLOCKED`,
    `8. Residual gaps (list remaining TODO items)`,
    `9. Next recommended task`,
    ``,
    `For construction-system work, also include:`,
    `- Records or schemas created (IDs, file paths)`,
    `- Whether CLI/MCP capability remains unimplemented`,
    ``,
    `Construction non-claim confirmation: confirm that no CLI, MCP, runtime,`,
    `or clinical capability was created unless this Settlement (${s.id}) explicitly targets them.`,
  ].join("\n");
}

export function assemblePromptSpec(input: AssemblyInput): string {
  const { settlement: s, territories, settlers } = input;
  const isoDate = new Date().toISOString().slice(0, 10);

  const header = [
    `<!-- Generated by healthos-steward generate-prompt -->`,
    `<!-- Settlement: ${s.id} -->`,
    `<!-- Generated: ${isoDate} -->`,
    `<!-- Non-canonical: this PromptSpec is a derived artifact, not an official doc -->`,
  ].join("\n");

  // Collect all settler invariants and forbidden moves for boundaries if needed
  void settlers; // settlers inform human readers via territory references; invariants already pulled from territories

  const sections = [
    section("system_role", buildSystemRole(s)),
    section("mission", buildMission(s)),
    section("context", buildContext(s, territories)),
    section("critical_precondition", buildCriticalPrecondition(s)),
    section("required_reading_before_writing", buildRequiredReading(s, territories)),
    section("canonical_nomenclature", CANONICAL_NOMENCLATURE),
    section("constitutional_and_runtime_boundaries", buildBoundaries(s, territories)),
    section("task_goals", buildTaskGoals(s)),
    section("allowed_files_to_touch", buildAllowedFiles(s)),
    section("forbidden_scope", buildForbiddenScope(s)),
    section("implementation_or_documentation_requirements", buildImplRequirements(s, territories)),
    section("tracking_updates", buildTrackingUpdates(s)),
    section("validation_required", buildValidationRequired(s)),
    section("git_workflow", buildGitWorkflow(s)),
    section("self_validation_checklist", buildSelfValidationChecklist(s)),
    section("final_response_required", buildFinalResponse(s)),
  ];

  return header + "\n\n" + sections.join("\n\n") + "\n";
}
