import { SettlementRecord } from "./settlement-parser.js";

export interface CriterionResult {
  criterion: string;
  result: "PASS" | "FAIL" | "UNVERIFIED";
  path?: string;
}

export interface FileCheckResult {
  path: string;
  exists: boolean;
}

export interface ValidationEvidence {
  criterionResults: CriterionResult[];
  fileCheckResults: FileCheckResult[];
}

export function buildValidationReport(
  settlement: SettlementRecord,
  evidence: ValidationEvidence
): string {
  const date = new Date().toISOString().slice(0, 10);

  const criterionRows = evidence.criterionResults
    .map((r) => `| ${r.result} | ${r.criterion} |`)
    .join("\n");

  const fileRows =
    evidence.fileCheckResults.length > 0
      ? evidence.fileCheckResults
          .map((r) => `| ${r.exists ? "PASS" : "FAIL"} | ${r.path} |`)
          .join("\n")
      : "| (none) | |";

  const validationCommandList =
    settlement.validationCommands.length > 0
      ? settlement.validationCommands.map((c) => `- ${c}`).join("\n")
      : "- (none listed)";

  const invariantList =
    settlement.invariants.length > 0
      ? settlement.invariants.map((inv, i) => `${i + 1}. ${inv}`).join("\n")
      : "1. (none listed)";

  const residualGapList =
    settlement.residualGaps.length > 0
      ? settlement.residualGaps.map((g) => `- ${g}`).join("\n")
      : "- (none listed)";

  const passCount = evidence.criterionResults.filter(
    (r) => r.result === "PASS"
  ).length;
  const failCount = evidence.criterionResults.filter(
    (r) => r.result === "FAIL"
  ).length;
  const unverifiedCount = evidence.criterionResults.filter(
    (r) => r.result === "UNVERIFIED"
  ).length;
  const totalCriteria = evidence.criterionResults.length;

  const existsCount = evidence.fileCheckResults.filter((r) => r.exists).length;
  const missingCount = evidence.fileCheckResults.filter(
    (r) => !r.exists
  ).length;
  const totalFiles = evidence.fileCheckResults.length;

  const cmdCount = settlement.validationCommands.length;

  return `---
# Validation Report: ${settlement.id}
<!-- Generated by healthos-steward validate-settlement -->
<!-- Generated: ${date} -->
<!-- Non-canonical: derived artifact, not an official doc -->

## Settlement
**id**: ${settlement.id}
**title**: ${settlement.title}
**status**: ${settlement.status}

## Done-criteria verification
| Result | Criterion |
|--------|-----------|
${criterionRows}

## Files-in-scope check
| Result | Path |
|--------|------|
${fileRows}

## Validation commands (must be run manually)
${validationCommandList}

## Invariant snapshot
${invariantList}

## Residual gaps
${residualGapList}

## Summary
- Done-criteria: ${passCount} PASS, ${failCount} FAIL, ${unverifiedCount} UNVERIFIED of ${totalCriteria}
- Files-in-scope: ${existsCount} exists, ${missingCount} missing of ${totalFiles}
- Validation commands: ${cmdCount} listed (must be run manually)

## Non-claims
This ValidationReport is a derived artifact generated by healthos-steward
from Settlement record fields and filesystem evidence. It does not authorize
merge decisions, clinical activity, runtime execution, or production-readiness
claims. Run all listed validation commands manually before marking a
Settlement COMPLETE.
---`;
}
